/// Provides an 'MVP' interface to a secrets manager
interface secrets-mvp {
    record secret {}

    /// Return the secret value associated with the handle
    get-secret: func(handle: secret) -> result<string, error>

    /// Set the secret value associated with the handle
    set-secret: func(handle: secret, value: string) -> result<_, error>

    enum error {
        success,
        invalid-argument,
    }
}

default world wasi-secrets {
    import secrets: self.secrets-mvp
}
