name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-guest-crate:
    name: Build Rust guest crate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install wit-bindgen-cli
      uses: actions-rs/cargo@v1
      with:
        command: install
        use-cross: false
        args: --git https://github.com/bytecodealliance/wit-bindgen wit-bindgen-cli
    - name: Generate guest crate
      run: ./scripts/generate-rust-guest.sh
