name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  abi-up-to-date:
    name: Check ABI files are up-to-date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest stable Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install wit-bindgen-cli
      uses: actions-rs/cargo@v1
      with:
        command: install
        use-cross: false
        args: --git https://github.com/bytecodealliance/wit-bindgen wit-bindgen-cli
    - name: Generate crate
      run: wit-bindgen guest rust --out-dir ./out --rustfmt wit/wasi-secrets.wit
